backend:
  # name: git-gateway
  # repo: TeeWallz/monty-astro-decap-cms
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: main
  squash_merges: true
  # open_authoring: true

# publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://astro-decapcms-starter.netlify.app/" # your site name

collections:
  - name: chump
    label: Chumps
    folder: src/content/chumps
    media_folder: /public/images/chumps
    public_folder: /public/images/chumps
    create: true
    format: frontmatter
    slug: "{{date}}{{name_slug}}"
    preview_path: chump/{{date}}
    fields:
      - { name: name, label: Name, widget: "string" }
      - { name: name_slug, default: "_short-name-with-dashes", label: "Short name with dashes", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        date_format: "YYYY-MM-DD" # e.g. 24.12.2021
        # time_format: "HH:mm" # e.g. 21:07
        # timeFormat: false
        # format: "YYYY-MM-DD"
        picker_utc: false
      - { name: date_chump, default: 1, label: "Order of chump on a given day", widget: "number", value_type: "int" }
      - { name: thanks, label: Thanks, widget: "string" }
      - { name: url, label: URL, widget: "string" }
      - { name: image, label: Image, widget: "image" }
      - { name: media, label: Media, widget: "list", required: false, field: { name: file, widget: "image" } }
